In [3]:
from google.colab import files

uploaded = files.upload()

Saving cleaned_sales_data.csv to cleaned_sales_data.csv

In [4]:
import pandas as pd

df = pd.read_csv("cleaned_sales_data.csv")
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ORDER_MONTH,ORDER_YEAR
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,NYC,NY,10022,USA,Not Specified,Yu,Kwai,Small,2,2003
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,Reims,Unknown,51100,France,EMEA,Henriot,Paul,Small,5,2003
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,Paris,Unknown,75508,France,EMEA,Da Cunha,Daniel,Medium,7,2003
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,Pasadena,CA,90003,USA,Not Specified,Young,Julie,Medium,8,2003
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,San Francisco,CA,00000,USA,Not Specified,Brown,Julie,Medium,10,2003

In [5]:
import pandas as pd
from scipy.stats import ttest_ind

In [7]:
df = pd.read_csv("cleaned_sales_data.csv")

df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ORDER_MONTH,ORDER_YEAR
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,NYC,NY,10022,USA,Not Specified,Yu,Kwai,Small,2,2003
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,Reims,Unknown,51100,France,EMEA,Henriot,Paul,Small,5,2003
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,Paris,Unknown,75508,France,EMEA,Da Cunha,Daniel,Medium,7,2003
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,Pasadena,CA,90003,USA,Not Specified,Young,Julie,Medium,8,2003
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,San Francisco,CA,00000,USA,Not Specified,Brown,Julie,Medium,10,2003

In [9]:
print(df.columns)

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE', 'ORDER_MONTH', 'ORDER_YEAR'],
      dtype='object')

In [11]:
import pandas as pd
from scipy.stats import ttest_ind

# Load dataset
df = pd.read_csv("cleaned_sales_data.csv")

# Create groups
large_sales = df[df['DEALSIZE'] == 'Large']['SALES']
small_sales = df[df['DEALSIZE'] == 'Small']['SALES']

In [12]:
t_stat, p_value = ttest_ind(large_sales, small_sales)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

T-Statistic: 106.49928235782062
P-Value: 0.0

In [13]:
print(df['DEALSIZE'].unique())

['Small' 'Medium' 'Large']

In [14]:
alpha = 0.05

if p_value < alpha:
    print("Reject the Null Hypothesis (H₀)")
    print("There is a statistically significant difference in average sales between Large and Small deals.")
else:
    print("Fail to Reject the Null Hypothesis (H₀)")
    print("There is no statistically significant difference in average sales between Large and Small deals.")

Reject the Null Hypothesis (H₀)
There is a statistically significant difference in average sales between Large and Small deals.

In [15]:
print("Average Sales (Large Deals):", large_sales.mean())
print("Average Sales (Small Deals):", small_sales.mean())

Average Sales (Large Deals): 8293.753248407646
Average Sales (Small Deals): 2061.6828003120127